### ISSUE TITLE
Can we avoid using the full Schema?

### ISSUE THREAD

**Issue by himanshu-wewentlive** [eturino/apollo-link-scalars#130]
* **I'm submitting a ...**
[X] question about how to use this project

* **Summary**
To avoid bundling a huge schema, can I generate a smaller schema consisting of only the fields I care about, matching the type information in my actual schema and passing just this small schema to the link?

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
E.g. something like

```
const schema = gql`
  type Event {
    start_time: Timestamp,
    end_time: Timestamp,
  }

  type Ticket {
    start_time: Timestamp,
    end_time: Timestamp,
  }

  type Order{ 
    created: Timestamp,
  }

  scalar Timestamp
`
const typesMap = {
  Timestamp: {
    parseValue(time) {
      return new Date(time * 1000);
    },
    serialize(date: Date) {
      return Math.round(date.getTime() * 1000);
    }
  }
};

export default  withScalars({ schema, typesMap })
```

Where Event, Ticket, Order have a bunch of other fields in my actual schema, which also has a bunch of other types. Would it cause any issues?
I generate this schema from my actual schema using a script.

TIA for the advice.

**Comment by eturino** [comment]
I think it probably should be ok, but you will need to add the root types (query, mutation, subscription). You could prune them. Otherwise, the `rootType` of an operation will not be found and the parsing will not be executed.

We use the schema to:
- get the list of leaf types, which gets merged with the given `typesMap`
- get the list of types of the inputs to serialize the values
- get the root types and follow the tree to parse the responses

To be able to do it without the root types and with only the relevant `input`s and `type`s, we would have to change the code to be able to transverse the tree "blindly" and look for `__typename`. It would need us to request the typename in our queries.

**Comment by eturino** [comment]
Please reopen if you need any help :)
